<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
  <xacro:include filename="$(find ros2_fra2mo)/urdf/utility_macro.xacro" />

  <xacro:macro name="fra2mo_base" > <xacro:property name="base_height" value="0.180" /> 
    <xacro:property name="base_radius" value="0.11" /> 
    <xacro:property name="base_mass" value="5" />
    <xacro:property name="wheel_mass" value="2.5" />
    <xacro:property name="wheel_radius" value="0.035" /> 
    <xacro:property name="wheel_axle" value="0.13" /> 
   
    <link name="base_footprint">
    </link>

    <link name="base_link">
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${base_mass}" />
        <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
      </inertial>
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_body.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Blue" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}" />
        </geometry>
        <origin xyz="0 0.0 ${(base_height/2.0)-0.05}" rpy="0 0 0" />
      </collision> 
      <collision>
        <geometry>
          <sphere radius="0.019" />
        </geometry>
        <origin xyz="-0.0825 0.0 -0.04" rpy="0 0 0" />
      </collision>        
    </link>
    
    <link name="cart_link">
      <visual>
        <geometry>
          <box size="0.3 0.20 0.05"/>
        </geometry>
        <material name="Grey">
          <color rgba="0.6 0.6 0.6 1"/>
        </material>
        <origin xyz="-0.1 0 0" rpy="0 0 0"/>
      </visual>

      <visual> <origin xyz="0.16 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.25 0.03 0.03"/>
        </geometry>
        <material name="DarkGrey">
           <color rgba="0.3 0.3 0.3 1"/>
        </material>
      </visual>

      <collision>
        <geometry>
          <box size="0.30 0.20 0.05"/>
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0"/>
      </collision>
      <inertial>
        <mass value="2.0"/> 
        <inertia ixx="0.02" ixy="0" ixz="0"
                 iyy="0.02" iyz="0"
                 izz="0.02"/>
      </inertial>
    </link>

    <joint name="cart_joint" type="fixed">
      <parent link="base_link"/>
      <child link="cart_link"/>
      <origin xyz="-0.29 0 -0.02" rpy="0 0 0"/>
    </joint>

    <xacro:cart_wheel name="cart_wheel_rl" parent="cart_link" x="-0.05" y="0.08"  z="-0.025"/>
    <xacro:cart_wheel name="cart_wheel_rr" parent="cart_link" x="-0.05" y="-0.08" z="-0.025"/>



    <link name="left_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black" />
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <link name="right_wheel_link">
      <visual> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <material name="Black"/>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </visual>
      <collision> 
        <geometry>
          <mesh filename="file://$(find ros2_fra2mo)/meshes/rl_fra2mo_wheel.stl" scale="0.001 0.001 0.001" />
        </geometry>
        <origin xyz="0 0 0" rpy="0 0 0" />
      </collision>
      <inertial>
        <origin xyz="0 0 0" />
        <mass value="${wheel_mass}" />
        <inertia ixx="0.001" ixy="0.0" ixz="0.0" iyy="0.001" iyz="0.0" izz="0.001" />
      </inertial>
    </link>

    <link name="d435_link">
    </link>
    <link name="lidar_link" />

    <joint name="base_footprint_joint" type="fixed">
      <parent link="base_footprint" />
      <child link="base_link" />
      <origin xyz="0.0 0.0 0.059" rpy="0 0 0" />
    </joint>
    <joint name="left_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="left_wheel_link" />
      <origin xyz="0.04025 0.062 -0.024" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="right_wheel_joint" type="continuous">
      <parent link="base_link" />
      <child link="right_wheel_link" />
      <origin xyz="0.04025 -0.062 -0.024" rpy="0 0 ${-M_PI}" />
      <axis xyz="0 -1 0" />
      <limit effort="100" velocity="100" />
      <dynamics damping="0.5" friction="0.01" />
    </joint>
    <joint name="d435_joint" type="fixed">
      <parent link="base_link" />
      <child link="d435_link" />
      <origin xyz="0.090925 0.0 0.06670" rpy="0 0 0" />
    </joint>
    <joint name="lidar_joint" type="fixed">
      <parent link="base_link" />
      <child link="lidar_link" />
      <origin xyz="0.0 0.0 0.125" rpy="0 0 0" />
    </joint>

    <transmission name="left_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="left_wheel_joint" />
      <actuator name="left_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>
    <transmission name="right_wheel_joint_trans">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="right_wheel_joint" />
      <actuator name="right_wheel_joint_motor">
        <mechanicalReduction>1</mechanicalReduction>
        <hardwareInterface>EffortJointInterface</hardwareInterface>
      </actuator>
    </transmission>

    <gazebo>
      <plugin name="ignition::gazebo::systems::DiffDrive" filename="libignition-gazebo-diff-drive-system.so">
        <left_joint>left_wheel_joint</left_joint>
        <right_joint>right_wheel_joint</right_joint>
        <wheel_separation>${wheel_axle}</wheel_separation>
        <wheel_radius>${wheel_radius}</wheel_radius>
        <odom_publish_frequency>50</odom_publish_frequency>
        <topic>/cmd_vel</topic>
      </plugin>
    </gazebo>
    
  <link name="container_link">
    
    <visual>
      <origin xyz="0 0 0.01"/>
      <geometry><box size="0.3 0.3 0.02"/></geometry>
      <material name="Blue_Dark"><color rgba="0 0 0.5 1"/></material>
    </visual>

    <visual>
      <origin xyz="0 0.145 0.075"/>
      <geometry><box size="0.3 0.01 0.15"/></geometry>
      <material name="Blue_Dark"/>
    </visual>

    <visual>
      <origin xyz="0 -0.145 0.075"/>
      <geometry><box size="0.3 0.01 0.15"/></geometry>
      <material name="Blue_Dark"/>
    </visual>

    <visual>
      <origin xyz="0.145 0 0.075"/>
      <geometry><box size="0.01 0.28 0.15"/></geometry>
      <material name="Blue_Dark"/>
    </visual>

    <visual>
      <origin xyz="-0.145 0 0.075"/>
      <geometry><box size="0.01 0.28 0.15"/></geometry>
      <material name="Blue_Dark"/>
    </visual>
    
    <collision>
      <origin xyz="0 0 0.075"/>
      <geometry><box size="0.3 0.3 0.15"/></geometry>
    </collision>
    
    <inertial>
       <mass value="0.3"/>
       <inertia ixx="0.008" ixy="0" ixz="0" iyy="0.008" iyz="0" izz="0.008"/>
    </inertial>
  </link>

    <joint name="container_joint" type="fixed">
      <parent link="cart_link" />
      <child link="container_link" />
      <origin xyz="-0.1 0.0 0.025" rpy="0 0 0" />
    </joint>
    
  
  </xacro:macro>
  
  <xacro:macro name="cart_wheel" params="name parent x y z">
    <link name="${name}">
      <visual>
        <geometry>
          <cylinder radius="0.03" length="0.02"/>
        </geometry>
        <material name="Black">
          <color rgba="0.1 0.1 0.1 1"/>
        </material>
        <origin rpy="1.5708 0 0"/>
      </visual>
      <collision>
        <geometry>
          <cylinder radius="0.03" length="0.02"/>
        </geometry>
        <origin rpy="1.5708 0 0"/>
      </collision>
      <inertial>
        <mass value="0.1"/>
        <inertia ixx="0.0001" ixy="0" ixz="0" iyy="0.0001" iyz="0" izz="0.0001"/>
      </inertial>
    </link>

    <joint name="${name}_joint" type="fixed">
      <parent link="${parent}"/>
      <child link="${name}"/>
      <origin xyz="${x} ${y} ${z}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${name}">
      <mu1>0.0</mu1>
      <mu2>0.0</mu2>
      <kp>1000000.0</kp>
      <kd>1.0</kd>
    </gazebo>
  </xacro:macro>

</robot>
